### ISSUE TITLE
Add ability to order operations 

### ISSUE THREAD

**Issue by chrisjhoughton** [trayio/falafel#13]
Probably the simplest way to do this is to add a `order` integer value on the schema which determines the priority the operation should have. Lowest goes first.

**Comment by chrisjhoughton** [comment]
Another alternative here is to add a sub folder structure, grouping by object type - like this:

```
connectors/
  pipedrive/
    deals/
      add_deal/
      update_deal/
    pipedrive/
      ...
```

That feels a lot cleaner - and makes it easily to factor in groupings into the UI at a later stage if needed.

**Comment by Johnbastian** [comment]
Made redundant by `default` parameter
