### ISSUE TITLE
Don't return the original input when there is a message error

### ISSUE THREAD

**Issue by alirussell** [trayio/falafel#14]
Falafel is returning the whole connector/operation `input` object when there is an error of any sort, which often includes sensitive information such as access tokens.  The returned payload gets stored in the step output by the cluster service which is not obfuscated in any way.

Need to remove the `input` object from the returned payload on errors

**Comment by chrisjhoughton** [comment]
Just looking over this now I'm back. The reasoning here totally makes sense - we don't want to have unencrypted data returned in the logs. 

As you say - the input being sent in isn't really necessary, because we can already see it in the input box of the logs panel.

**Comment by chrisjhoughton** [comment]
PR for this here https://github.com/trayio/falafel/pull/15

**Comment by chrisjhoughton** [comment]
Closed via https://github.com/trayio/falafel/pull/15
