### ISSUE TITLE
Set the user agent as tray.io, including the falafel version in requests

### ISSUE THREAD

**Issue by chrisjhoughton** [trayio/falafel#26]
Useful for debugging etc.

**Comment by Johnbastian** [comment]
@chrisjhoughton 
This makes more sense to add in Threadneedle.
However, since threadneedle is "public", I'm not sure if it's the best idea.
How about adding it as default in the generator?

**Comment by chrisjhoughton** [comment]
Hmm leave it then that gets a bit complicated for such a trivial feature
