### ISSUE TITLE
Improving file handling

### ISSUE THREAD

**Issue by chrisjhoughton** [trayio/falafel#39]
## Current situation

Currently falafel supports file uploads and downloads, like so:
### "Download" attachment

Downloads an attachment **from** a third party service, e.g. Salesforce, and saves it to S3. The flow is: 

`Get file contents > Store in memory (buffer) > Upload to S3`
### "Upload" attachment

Uploads an attachment **to** a third party service, e.g. Asana. The flow is: 

`Download file from S3 URL > Store in memory (buffer) > Upload to service`
## Key issue

Files are stored in memory. For an 8MB zip file, a 1.5GB lambda function ran out of memory while executing. No idea why, but it looks like an exponential effect.
## New approach

Use the filesystem to store the files temporarily in the connector Lambda filesystem, rather than memory. This approach has already been tested and working on production with the Salesforce connector - it's at least an order of magnitude more efficient, and unlikely to be exponential. 

One of the key advantages here is that we can make use of Node.js streams, which allow the data to be passed along as it is output & read, rather than having to store everything in memory first and then send it all at once.
### Downloads

The flow will now be:  

`Get file contents > Output directly to temp file > Upload file to S3`
### Uploads

The flow will now be:

`Download file from S3 > Output to temp file > Upload file to service`

---
### Add a `fileHandler` parameter to models

Both of the above flows require a temporary file to be created and read from on the local filesystem. 

Lambda allows the user to write to the local filesystem in the `/tmp` folder, and falafel models already allow the outputting to a file (for downloads) with the following options:

``` js
options: {
  output: '{{temp_file}}'
}
```

Similarly for uploads, the S3 file needs to be downloaded to a temporary file on the filesystem, so a `temp_file` will also be needed.

**Proposal:** add a new `fileHandler: true` option to models, to be specified on any download or upload operations. 

The above will cause an additional `temp_file` input parameter to be added to the incoming message from the Cluster Service, in the format `/tmp/guid`.

The connector can then use this parameter to download & upload from, without having to go into the detail of adding this parameter itself. 
### File upload API change

Backwards compatibility is important here. 
#### Upload

`falafel.files.upload` - currently takes the following input:

``` js
{
  name: 'my-file-name.pdf',
  contents: Buffer(....)
}
```

New versions should take:

``` js
{
  name: 'my-file-name.pdf',
  file: '{{temp_file}}'
}
```
#### Download

`falafel.files.download` - the input won't change here, but the output will. It currently outputs:

``` js
{
  contents: Buffer(...),
  name: 'my-file-name.pdf',
  mime_type: 'application/pdf',
  expires: 124513421321
}
```

New versions should output:

``` js
{
  file: '{{temp_file}}',
  name: 'my-file-name.pdf',
  mime_type: 'application/pdf',
  expires: 124513421321
}
```

**Comment by chrisjhoughton** [comment]
Note that this proposal is a breaking change, so:

* A major version should be bumped on falafel
* All existing connectors will need to be updated to use the new file approach

**Comment by chrisjhoughton** [comment]
Waiting on approval from @alirussell

**Comment by Johnbastian** [comment]
This looks like it has been completed on the falafel side.
I've created an issue in the connector's repo to have the relevant connectors updated: https://github.com/trayio/connectors/issues/409
