### ISSUE TITLE
Auto-handle some more error status codes

### ISSUE THREAD

**Issue by chrisjhoughton** [trayio/falafel#45]
For a lot of error types, we respond with "Invalid status code", which isn't at all helpful for the user. We already respond with "Not found" for 404, for example - what else could we make simpler here? 

Definitely handle:

* 429 - rate limits 

See http://www.restapitutorial.com/httpstatuscodes.html

These are actually handled in threadneedle (rather than falafel) here https://github.com/trayio/threadneedle/blob/master/lib/addMethod/validateExpects.js#L72

Note that you'll need unit tests for anything you add too https://github.com/trayio/threadneedle/blob/master/tests/validateExpects_test.js#L38

First step - I'd recommend putting together a list of status codes we should handle, and the error message for each. (Note that for many of the 5xx errors, we might want to use the same error message)

**Comment by Johnbastian** [comment]
@chrisjhoughton So this issue should be in needle instead of falafel?

**Comment by chrisjhoughton** [comment]
Yes it should, feel free to move it over

**Comment by Johnbastian** [comment]
https://github.com/trayio/threadneedle/issues/8 is done
