### ISSUE TITLE
Idea: automatic date formatting

### ISSUE THREAD

**Issue by chrisjhoughton** [trayio/falafel#48]
Different systems have different date formats. Example:

* Salesforce: 2016-02-18T21:54:33.000+0000
* Zendesk: 2016-02-18T21:54:33Z

Zendesk actually rejects dates that are in the Salesforce format - causing an error in the workflow. The data needs to be formatted in a JavaScript step to be able to pass a date to Zendesk correctly.

__Proposal:__
* Add a "date" format to the connectors json
* Add a "date_format" key to schema properties to indicate the format a date should have
The connector should automatically try and convert the date to the desired format 

__Why?__
* Simpler and more reliable for users!

**Comment by chrisjhoughton** [comment]
FYI I'm going to be prototyping this over the next few days

**Comment by Johnbastian** [comment]
Looks like this is now done, so I'll close the issue.
